export const LIGHTS_OUT_GRID_SIZE = 3;

export const LIGHTS_OUT_NUM_CELLS = LIGHTS_OUT_GRID_SIZE * LIGHTS_OUT_GRID_SIZE;

export const LIGHTS_OUT_ANIMATION_DURATION_MS = 300;

export const LIGHTS_OUT_SCRAMBLE_MIN_MOVES = 10;

export const LIGHTS_OUT_SCRAMBLE_MAX_MOVES = 19;