export const SLIDER_PUZZLE_GRID_SIZE = 3;
export const SLIDER_PUZZLE_NUM_TILES =
	SLIDER_PUZZLE_GRID_SIZE * SLIDER_PUZZLE_GRID_SIZE;
export const SLIDER_PUZZLE_TILE_SIZE_PX = 100;
export const SLIDER_PUZZLE_ANIMATION_DURATION_MS = 300;